services:
  - type: web
    name: fushimitools-youtube
    runtime: docker
    rootDir: youtube-downloader-server
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: WORKER_SHARED_SECRET
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false

  - type: web
    name: fushimitools-qr
    runtime: python
    rootDir: qr-generator
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: APP_URL
        sync: false
